#!/usr/bin/bash 
BASEDIR=$(dirname "$0")

MALLOC_INTERPOSE_DEPTH=${MALLOC_INTERPOSE_DEPTH:-50} MALLOC_INTERPOSE_SHIFT=${MALLOC_INTERPOSE_SHIFT:-10} MALLOC_INTERPOSE_COMPRESSION=${MALLOC_INTERPOSE_COMPRESSION:-10000002} MALLOC_INTERPOSE_BUCKET_SIZE=${MALLOC_INTERPOSE_BUCKET_SIZE:-65535} LD_PRELOAD=${BASEDIR}/../lib/libMallocHook.so "$@"
